config/routes.rb
Kazanie::Application.routes.draw do

  devise_for :users

  resources :projects, :only => [:index, :show]

  match "admin/projects/:id/masterpieces" => "admin/projects#show", :via => "get"
  match "admin/projects/:project_id/masterpieces/:id/focals" => "admin/masterpieces#show", :via => "get"

  namespace :admin do
    resources :projects do

      resources :masterpieces, :except => [:index] do
        collection do
          post 'sort'
        end

        resources :focals, :except => [:index] do
          collection do
            post 'sort'
          end
        end
      end

    end
  end

  root :to => "projects#index"

end

app/models/masterpiece.rb
class Masterpiece < ActiveRecord::Base
  belongs_to :project
  has_many :focals

  image_accessor :image

  scope :sorted, order("masterpieces.position ASC")

  validates_presence_of :project
  validates_presence_of :title
  validates_presence_of :text
  validates_presence_of :image

end

app/controllers/admin/masterpieces_controller.rb
class Admin::MasterpiecesController < ApplicationController

  before_filter :authenticate_user!
  before_filter :set_project

  # GET /admin/masterpieces/1
  # GET /admin/masterpieces/1.xml
  def show
    @masterpiece = Masterpiece.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @masterpiece }
    end
  end

  # GET /admin/masterpieces/new
  # GET /admin/masterpieces/new.xml
  def new
    @masterpiece = Masterpiece.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @masterpiece }
    end
  end

  # GET /admin/masterpieces/1/edit
  def edit
    @masterpiece = Masterpiece.find(params[:id])
  end

  # POST /admin/masterpieces
  # POST /admin/masterpieces.xml
  def create
    @masterpiece = Masterpiece.new(params[:masterpiece])
    @masterpiece.project = @project

    respond_to do |format|
      if @masterpiece.save
        format.html { redirect_to([:admin, @project, @masterpiece], :notice => 'Masterpiece was successfully created.') }
        format.xml  { render :xml => @masterpiece, :status => :created, :location => @masterpiece }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @masterpiece.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/masterpieces/1
  # PUT /admin/masterpieces/1.xml
  def update
    @masterpiece = Masterpiece.find(params[:id])

    respond_to do |format|
      if @masterpiece.update_attributes(params[:masterpiece])
        format.html { redirect_to([:admin, @project, @masterpiece], :notice => 'Masterpiece was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @masterpiece.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/masterpieces/1
  # DELETE /admin/masterpieces/1.xml
  def destroy
    @masterpiece = Masterpiece.find(params[:id])
    @masterpiece.destroy

    respond_to do |format|
      format.html { redirect_to([:admin, @project], :notice => 'Masterpiece was successfully deleted.') }
      format.xml  { head :ok }
    end
  end

  def sort
    params[:order].each do |pos, id|
      f = Masterpiece.find(id)
      f.position = pos.to_i
      f.save
    end
    render :nothing => true
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end
end

app/helpers/admin/masterpieces_helper.rb
module Admin::MasterpiecesHelper
end

app/views/admin/masterpieces/_focals.haml
.h2 Focals

.table
  .header
    .grid_2 Image 
    .grid_4 Title
    .grid_6 Text

  .clear

  .records.sortable{ :url => focals_sortable_url }
    - @masterpiece.focals.sorted.each do |focal|
      .record{ :id => focal.id }
        .grid_2= image_tag focal.image.thumb("100x100#").url
        .grid_4= focal.title
        .grid_6= format_text(focal.text)
        .grid_4
          = link_to 'view', project_masterpiece_focal_path(@project, @masterpiece, focal)
          \/
          = link_to 'edit', edit_admin_project_masterpiece_focal_path(@project, @masterpiece, focal)
          \/
          = button_to 'delete', [:admin, @project, @masterpiece, focal], :confirm => 'Are you sure?', :method => :delete, :class => 'delete'
        .clear

  .clear

app/views/admin/masterpieces/_form.html.haml
= form_for [:admin, @project, @masterpiece], :html => {:multipart => true} do |f|
  -if @masterpiece.errors.any?
    #error_explanation.error
      %h2= "#{pluralize(@masterpiece.errors.count, "error")} prohibited this masterpiece from being saved:"
      %ul
        - @masterpiece.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :text
    = f.text_area :text
  .field
    = f.label :image_uid, 'Image (leave blank to keep current image)'
    = f.file_field :image
  .actions
    = f.submit 'Save'

app/views/admin/masterpieces/edit.html.haml
.breadcrumbs
  = link_to 'all projects', admin_projects_path
  >
  = link_to @project.name, [:admin, @project]
  >
  = link_to @masterpiece.title, [:admin, @project, @masterpiece]
  >
  edit

.h1 Edit Masterpiece

= render 'form'

%br

= link_to 'back to project', edit_admin_project_path(@project)
\/
= link_to 'view masterpiece', project_masterpiece_path(@project, @masterpiece)
\/
= link_to 'new focal', new_admin_project_masterpiece_focal_path(@project, @masterpiece)

%br

= render :partial => 'focals'

app/views/admin/masterpieces/new.html.haml
.breadcrumbs
  = link_to 'all projects', admin_projects_path
  >
  = link_to @project.name, [:admin, @project]
  >
  new masterpiece

.h1 New Masterpiece

= render 'form'

%br

= link_to 'back to project', edit_admin_project_path(@project)

app/views/admin/masterpieces/show.html.haml
.breadcrumbs
  = link_to 'all projects', admin_projects_path
  >
  = link_to @project.name, [:admin, @project]
  >
  = @masterpiece.title

.h1 Masterpiece

.title= @masterpiece.title
.image= image_tag @masterpiece.image.thumb("300x300>").url
.text= format_text(@masterpiece.text)

= link_to 'back to project', edit_admin_project_path(@project)
\/
= link_to 'edit masterpiece', edit_admin_project_masterpiece_path(@project, @masterpiece)
\/
= link_to 'view masterpiece', project_masterpiece_path(@project, @masterpiece)
\/
= link_to 'new focal', new_admin_project_masterpiece_focal_path(@project, @masterpiece)

%br

= render :partial => 'focals'