config/routes.rb
Kazanie::Application.routes.draw do

  devise_for :users

  resources :projects, :only => [:index, :show]

  match "admin/projects/:id/masterpieces" => "admin/projects#show", :via => "get"
  match "admin/projects/:project_id/masterpieces/:id/focals" => "admin/masterpieces#show", :via => "get"

  namespace :admin do
    resources :projects do

      resources :masterpieces, :except => [:index] do
        collection do
          post 'sort'
        end

        resources :focals, :except => [:index] do
          collection do
            post 'sort'
          end
        end
      end

    end
  end

  root :to => "projects#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :masterpieces

  validates_presence_of :name

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController

  before_filter :authenticate_user!

  # GET /admin/projects
  # GET /admin/projects.xml
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /admin/projects/1
  # GET /admin/projects/1.xml
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /admin/projects/new
  # GET /admin/projects/new.xml
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /admin/projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /admin/projects
  # POST /admin/projects.xml
  def create
    @project = Project.new(params[:project])
    @project.user = current_user

    respond_to do |format|
      if @project.save
        format.html { redirect_to([:admin, @project], :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/projects/1
  # PUT /admin/projects/1.xml
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to([:admin, @project], :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/projects/1
  # DELETE /admin/projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(admin_projects_url, :notice => 'Project was successfully deleted.') }
      format.xml  { head :ok }
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    redirect_to admin_projects_path, :notice => flash[:notice], :alert => flash[:alert]  if user_signed_in?
    @projects = Project.all.paginate :page => params[:page], :per_page => 10
  end

  def show
    @project = Project.find(params[:id])
    render :layout => "project"
  end

end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  
  def format_text(text)
    simple_format h(text).gsub(/\r\n/, '<br />')
  end

end

app/views/admin/projects/_form.html.haml
= form_for [:admin, @project] do |f|
  -if @project.errors.any?
    #error_explanation.error
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name

    = f.submit 'Save'

app/views/admin/projects/_masterpieces.haml
.h2 Masterpieces

.clear

.table
  .header
    .grid_2 Image
    .grid_4 Title
    .grid_6 Text

  .clear

  .records.sortable{ :url => masterpieces_sortable_url }
    - @project.masterpieces.sorted.each do |masterpiece|
      .record{ :id => masterpiece.id }
        .grid_6
          .grid_2.alpha= image_tag masterpiece.image.thumb("100x100#").url
          .grid_4.omega= masterpiece.title
          .clear
          .subrecords.grid_6.alpha.omega
            .thumbs
              - masterpiece.focals.sorted.each do |focal|
                = image_tag focal.image.thumb("30x30#").url
            .count= "(#{masterpiece.focals.count} focals)"
        .grid_6= format_text(masterpiece.text)
        .grid_4
          = link_to 'view', project_masterpiece_path(@project, masterpiece)
          \/
          = link_to 'edit', edit_admin_project_masterpiece_path(@project, masterpiece)
          \/
          = button_to 'delete', [:admin, @project, masterpiece], :confirm => 'Are you sure?', :method => :delete, :class => 'delete'
      .clear

  .clear

app/views/admin/projects/edit.html.haml
.breadcrumbs
  = link_to 'all projects', admin_projects_path
  >
  = link_to @project.name, [:admin, @project]
  >
  edit

.h1 Edit Project

= render 'form'

%br

= link_to 'back to all projects', admin_projects_path
\/
= link_to 'view project', @project
\/
= link_to 'new masterpiece', new_admin_project_masterpiece_path(@project)

%br

= render :partial => 'masterpieces'

app/views/admin/projects/index.html.haml
.h1 Projects

.table
  .header
    .grid_5
      Name
    .grid_3
      Created By
    .grid_3
      Last Updated
  
  .clear

  .records
    - @projects.each do |project|
      .record
        .grid_5= project.name
        .grid_3= project.user.email
        .grid_3= "#{time_ago_in_words(project.updated_at)} ago"
        .grid_4
          = link_to 'view', project
          \/
          = link_to 'edit', edit_admin_project_path(project)
          \/
          = button_to 'delete', [:admin, project], :confirm => 'Are you sure?', :method => :delete, :class => 'delete'
        .clear
        .subrecords.grid_16
          .thumbs
            - project.masterpieces.sorted.each do |masterpiece|
              = image_tag masterpiece.image.thumb("30x30#").url
          .count= "(#{project.masterpieces.count} masterpieces)"
      .clear

%br

= link_to 'new project', new_admin_project_path
    

app/views/admin/projects/new.html.haml
.breadcrumbs
  = link_to 'all projects', admin_projects_path
  >
  new project

.h1 New Project

= render 'form'

%br

= link_to 'back to all projects', admin_projects_path

app/views/admin/projects/show.html.haml
.breadcrumbs
  = link_to 'all projects', admin_projects_path
  >
  = @project.name

.h1 Project

.title= @project.name

= link_to 'back to all projects', admin_projects_path
\/
= link_to 'edit project', edit_admin_project_path(@project)
\/
= link_to 'view project', @project
\/
= link_to 'new masterpiece', new_admin_project_masterpiece_path(@project)

%br

= render :partial => 'masterpieces'